[workspace]
authors = ["mismorgano <mismorgano@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "DeepLearning"
platforms = [
  { platform = "linux-64", cuda = "13" },
  { platform = "win-64", cuda = "13" }
]
version = "0.1.0"

[tasks]


[dependencies]
pytorch = ">=2.12.0,<3"
torchvision = ">=0.27.0,<0.28"

[feature.dev.dependencies]
matplotlib = "*"

[environments]
dev = ["dev"]
